- name: Upload key file
  template:
    src: account.json.j2
    dest: ~/account.json
    owner: ubuntu
    mode: 0600

- name: Activate and authenticate gcloud service account
  shell: gcloud auth activate-service-account {{ gcp_serviceaccount_client_email }} --key-file=/home/ubuntu/account.json
