- copy:
    src: run_commits_batch.sh
    dest: ~/run_commits_batch.sh
    owner: ubuntu
    mode: 0755

- cron:
    name: ""
    user: ubuntu
    weekday: 1
    hour: 0
    minute: 1
    job: "~/run_commits_batch.sh"
    state: absent
