- name: Add tickerdumper group
  group:
    name: tickerdumper
    state: present
  become: true

- name: Add user ubuntu to tickerdumper group
  user:
    name: ubuntu
    groups: tickerdumper
    append: yes
  become: true

- name: Create filesystem on data disk
  filesystem:
    fstype: ext4
    dev: /dev/disk/by-id/google-crypto-data-disk
  become: true

- name: Mount data disk
  mount:
    path: /mnt/crypto-data
    src: /dev/disk/by-id/google-crypto-data-disk
    fstype: ext4
    state: mounted
  become: true

- name: Chgroup data disk to tickerdumpers
  file:
    path: /mnt/crypto-data
    group: tickerdumper
    mode: 0775
  become: true

- name: Download ticker dumper
  get_url:
    url: https://github.com/lauripiispanen/poloniex-ticker-dumper/releases/download/0.1/tickerdumper
    dest: /usr/local/bin/tickerdumper
    mode: 0777
  become: true

- name: Setup ticker dumper service
  template:
    src: tickerdumper.service.j2
    dest: /etc/systemd/system/tickerdumper.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Start ticker dumper service
  service:
    name: tickerdumper
    state: started
    enabled: yes
  become: true
